package com.ftk.pg.util;

public interface Constants {

	String PAYMENT_URL = "PAYMENT_URL";
	String RETURN_URL = "PAYNETZ_RETURN_URL";
	String PAYNOW_URL = "PAYNOW_URL";

	String BOB_PROPERTIES_PATH_KEY = "BOB_PROPERTIES_PATH_KEY"; // C:\\Users\\MEENAKSHI\\Documents\\bob\\bob-log;
	String BOB_ALIAS_KEY = "BOB_ALIAS_KEY"; // BOBTESTME;
	String BOB_RU_KEY = "BOB_RU_KEY";

	String PAYU_PROPERTIES_PATH_KEY = "PAYU_PROPERTIES_PATH_KEY";
	String PAYU_ALIAS_KEY = "PAYU_ALIAS_KEY";
	String PAYU_RU_KEY = "PAYU_RU_KEY";

	String GETEPAY_SSL_FILE_KEY = "GETEPAY_SSL_PATH";
	String GETEPAY_SSL_PASS_KEY = "GETEPAY_SSL_PASS";

	String CHALLAN_BASE_PATH = "CHALLAN_BASE_PATH";
	String CHALLAN_IFSC_CODE = "CHALLAN_IFSC_CODE";

	String REGISTER_MANDATE_URL = "REGISTER_MANDATE_URL";
	String VALIDATION_MANDATE_URL = "VALIDATION_MANDATE_URL";

	String AUQR_CONFIG_API_KEY = "AUQR_CONFIG_API_KEY";
	String AUQR_CONFIG_API_ENC128 = "AUQR_CONFIG_API_ENC128";
	String AUQR_CONFIG_API_ENC256="AUQR_CONFIG_API_ENC256";
	String AUQR_CONFIG_API_MODSTRING="AUQR_CONFIG_API_MODSTRING";
	String AUQR_CONFIG_API_EXPSTRING="AUQR_CONFIG_API_EXPSTRING";
	String AUQR_CONFIG_API_URL="AUQR_CONFIG_API_URL";
	String AUQR_CONFIG_API_USER="AUQR_CONFIG_API_USER";

	String AUQR_CONFIG_API_MERCHANTCONFIG="AUQR_CONFIG_API_MERCHANTCONFIG";

	String QR_PATH="/media/shared/dynamicqrpath/";
//	String QR_PATH="/mnt/efs/lambda/pg/dynamicqrpath/";
	
	
	String TXN_SYNC_API_URL = "TXN_SYNC_API_URL";
	String TXN_SYNC_API_KEY = "TXN_SYNC_API_KEY";
	String GETEPAY_ICICI_PRIVATE_KEY = "GETEPAY_ICICI_PRIVATE_KEY";

}
